source 'https://github.com/CocoaPods/Specs.git'

target 'AFULoginSDK', :exclusive => true do
  pod "AFULoginSDK", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AFULoginSDK", :path => "../"

  
end
